spring:
  application:
    name: multrabbitsb32
  webflux:
    base-path: /api
  rabbitmq:
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  multirabbitmq:
    enabled: true
    connections:
      dev:
        host: localhost
        port: 5672
        virtual-host: /
        username: guest
        password: guest
      dev2:
        host: localhost
        port: 5673
        virtual-host: /
        username: guest
        password: guest
    default-connection: dev