spring:
  application:
    name: multrabbitsb32
  webflux:
    base-path: /api
  multirabbitmq:
    enabled: true
    connections:
      dev:
        host: localhost
        port: 5672
        virtual-host: /
        username: guest
        password: guest
      dev2:
        host: localhost
        port: 5673
        virtual-host: /
        username: guest
        password: guest
#      dev3:
#        host: localhost
#        port: 5672
#        virtual-host: /
#        username: guest
#        password: guest
    default-connection: dev