spring:
  application:
    name: multrabbitsb32
  webflux:
    base-path: /api
  rabbitmq:
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  multirabbitmq:
    enabled: true
    connections:
      dev:
        host: ---------
        port: 5671
        virtual-host: --------
        username: --------
        password: -------------
        listener:
          direct:
            acknowledge-mode: manual
          simple:
            acknowledge-mode: manual
        ssl:
          enabled: true
      dev2:
        host: localhost
        port: 5673
        virtual-host: /
        username: guest
        password: guest
    default-connection: dev